---
title             : "Code, Graphs, and Animation"
shorttitle        : "Covid 19"
author: 
  - name          : "Gerardo Palacios"
    affiliation   : "1,2"
affiliation:
  - id            : "1"
    institution   : "DSC 430 - Data Visualization"
  - id            : "2"
    institution   : "DePaul University"
wordcount         : "X"
bibliography      : ["r-references.bib"]
floatsintext      : yes
figsintext        : yes
figurelist        : yes
tablelist         : yes
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no
documentclass     : "apa6"
classoption       : "man"
#output            : papaja::apa6_pdf
output            : html_document
editor_options: 
  chunk_output_type: console
---

```{r setup libraries, include = FALSE}
library("papaja")
library(dplyr)
library(mosaic)
library(lubridate)
library(ggplot2)
library(knitr)
library(kableExtra)
library(cowplot)
library(scales)
library('vioplot')
library(ggmosaic)
library(psych)
library("tidyr")
library(corrplot)
library(gganimate)
library(tidyquant)
library(countrycode)
library(sp)
library(rworldmap)
source("C:\\Users\\G_MAN\\OneDrive\\DePaul\\Advanced Data Anlaysis\\Functions\\SummaryFunctions.R")

```


```{r setup colors, include = FALSE}
pallets <- list(
  'diverging'=c(
    'Spectral',
    'RdYlGn',
    'RdYlBu',
    'RdGy',
    'RdBu',
    'PuOr',
    'PRGn',
    'PiYG',
    'BrBG'),
  
  'qualitative'= c(
    'Set1',
    'Set2',
    'Set3',
    'Pastel2',
    'Pastel1',
    'Paired',
    'Dark2',
    'Accent'),
    
  'sequential'=c(
    'YlOrRd',
    'YlOrBr',
    'YlGnBu',
    'YlGn',
    'Reds',
    'RdPu',
    'Purples',
    'PuRd',
    'PuBuGn',
    'PuBu',
    'OrRd',
    'Oranges',
    'Greys',
    'Greens',
    'GnBu',
    'BuPu',
    'BuGn',
    'Blues')
)

```

```{r setup names, include = FALSE}
# Define plot titles
titles <- list("title1" = "Continent vs Stringency Responses", 
                "title2" = "Distribution of New Cases by Date and Stringency Level", 
                "title3" = "Weekly Deaths Per Weekly Total Cases by Time, Continent and Stringency Index",
                "title4" = "Weekly Deaths Per Weekly Total Cases by Time, Continent and Stringency Index",
                "title5" = "Total Deaths")


subtitles <- list("subtitle1" = "Between March 2020 and October 2020", 
                "subtitle2" = "Between March 2020 and October 2020", 
                "subtitle2a" = "Week of : {frame_time}", 
                "subtitle3" = "Smoothed LOESS - Between March 2020 and October 2020", 
                "subtitle4" = "Smoothed LOESS - Between March 2020 and October 2020",
                "subtitle4" = "Between March 2020 and October 2020",
                "subtitle5" = "Between March 2020 and October 2020",
                "subtitle5a" = "Week of : {current_frame}")


```


```{r analysis-preferences, include = FALSE}
# Seed for random number generation
set.seed(123)
options(scipen = 999)  
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
r_refs("r-references.bib")

```

# Data Preprocess
```{r intel_1, include = TRUE,echo=TRUE,warning=FALSE}
# Import data
data <- read.table("cleandata_rm.csv", header=TRUE, sep=",")

# Convert to date types
data$date <- as.Date(as_date(data$date,format = '%Y-%m-%d'))

# Remove special characters
data$continent <- gsub("\n"," " , data$continent ,ignore.case = TRUE)

data <- data %>% mutate_if(is.character,as.factor)

# Bin the stringency index into 4 parts
data$stry_index <- as.factor(ifelse(
  data$stry_index <= 25, 'No Response' , ifelse( 
   data$stry_index > 25 & data$stry_index <= 50 , 'Least Stringent', ifelse(
    data$stry_index > 50 & data$stry_index <= 75 ,'Moderately Stringent',ifelse( 
     data$stry_index > 75 ,  'Most Stringent','None')))))

# Define mode function
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

# Copy standardized raw data set
data_raw <- data

# Pivot and summarize data by 7 days
data <- data %>% group_by(
  continent=continent,
  date=floor_date(date, "7 days"),
  
  ) %>%
   summarize(
     location = getmode(location),
     new_cases=mean(new_cases),
     new_deaths=mean(new_deaths),
     stry_index=getmode(stry_index),
     total_deaths=mean(total_deaths),
     total_cases = mean(total_cases),
     month = mean(month),
     population=mean(population))

# Add new date format
data$date2 <- as.POSIXct(as.yearmon(data$date,
                      format = "%Y-%m-%d"),
                      format = "%m-%d-%Y")

data_raw$date2 <- as.POSIXct(as.yearmon(data_raw$date,
                      format = "%Y-%m-%d"),
                      format = "%m-%d-%Y")

# Create new variable 
data$deaths_per_cases <- (data$total_deaths/data$total_cases) * 100
data_raw$deaths_per_cases <- (data_raw$total_deaths/data_raw$total_cases) * 100

# Manually apply log base 10 scale
data$new_cases <- log(data$new_cases+1,10)
data$new_deaths <- log(data$new_deaths+1,10)

data_raw$new_cases <- log(data_raw$new_cases+1,10)
data_raw$new_deaths <- log(data_raw$new_deaths+1,10)

data_raw = na.omit(data_raw)
data = na.omit(data)

```

\clearpage

# Mosaic Plot
```{r p1, include = TRUE, echo = TRUE, fig.align='center',fig.width= 8,fig.height= 8,fig.cap="Covid 19 - Stringency Level vs Continent",warning=FALSE}

fill_1 <-   scale_fill_brewer(
              name="Stringency\nResponse\nLevel", 
              direction = 1,
              palette = pallets$qualitative[7])

p1 <- ggplot(data = data_raw) + 
      geom_mosaic(aes(x=product(stry_index,continent),fill=stry_index,size=3)) +

      annotate(
      geom="text", x=.225,y=-0.05,
      label="Africa", color="black", size=5) + 

      annotate(
      geom="text", x=.59,y=-0.05,
      label="Asia", color="black", size=5) +

      annotate(
      geom="text", x=.75,y=-0.05,
      label="Europe", color="black", size=5) + 

      annotate(
      geom="text", x=.85,y=-0.05,
      label="North\nAmerica", color="black", size=5) + 

      annotate(
      geom="text", x=.97,y=-0.05,
      label="South\nAmerica", color="black", size=5) + 
  
  labs(fill='Stringency Index',title = titles$title1, subtitle = subtitles$subtitle1) + theme(legend.position = 'bottom',axis.title = element_text(size = 7)) + fill_1
      

p1

```

\clearpage

# Animated Ridge Distribution
```{r p2, include = TRUE, echo = TRUE, fig.align='center',fig.width= 8,fig.height= 7,fig.cap="Distributions by Stringency Level and Continent",warning=FALSE}

sec_breaks <- c(10,100, 1000, 10000, 100000, 1000000)

p2 <- ggplot(data=data_raw, aes(y = date2, x = new_cases,fill=stry_index)) + 
      geom_density_ridges() + 
      scale_x_continuous(
        sec.axis = sec_axis(trans = ~10^.,
        breaks = sec_breaks,
        labels = format(sec_breaks, big.mark=",", scientific=FALSE),
        name = 'New Cases Per Week - Exponential scale')) + 
      labs(title = titles$title2, subtitle = subtitles$subtitle2,fill='Stringency Index') + ylab('Date') + 
      xlab('New Cases Per Week - Logorithmic scale (Log base 10)') + theme(legend.position = 'bottom') + fill_1


p2_animated <- p2 + transition_time(date2) + labs(subtitle = subtitles$subtitle2a)
animate(p2_animated,fps = 20)
anim_save(paste(titles$title2,'gif',sep = '.'))

```

\clearpage

# Layered Smoothed LOESS by Time, Continent, and Stringency Level
```{r p3, include = TRUE, echo = TRUE, fig.align='center',fig.width= 8,fig.height= 10,fig.cap="Smoothed LOESS by Continent and Stringency Level ",warning=FALSE}

color_2 <-   scale_color_brewer(
              name="Continents", 
              direction = 1,
              palette = pallets$qualitative[2])


lwd = 2.25
p3 <- ggplot() + 
  geom_smooth(data=data[which(data$continent=='Africa'),],aes(x=date,y=deaths_per_cases,linetype =stry_index,color=continent),lwd =lwd) +    geom_smooth(data=data[which(data$continent=='Asia'),],aes(x=date,y=deaths_per_cases,linetype =stry_index,color=continent),lwd =lwd)  +
  geom_smooth(data=data[which(data$continent=='Europe'),],aes(x=date,y=deaths_per_cases,linetype =stry_index,color=continent),lwd =lwd)+
  geom_smooth(data=data[which(data$continent=='North America'),],aes(x=date,y=deaths_per_cases,linetype =stry_index,color=continent),lwd =lwd)  + geom_smooth(data=data[which(data$continent=='South America'),],aes(x=date,y=deaths_per_cases,linetype =stry_index,color=continent),lwd =lwd) +
  scale_x_date(date_breaks = '1 month') + 
  scale_y_continuous(n.breaks = 15) + theme(legend.position = 'bottom') +
  labs(title = titles$title3,subtitle = subtitles$subtitle3,linetype='Stringency Response') + 
  ylab('Weekly Deaths Per Weekly Total Cases (%)') + 
  xlab('Date') + theme(axis.text.x.bottom = element_text(angle = 45,hjust = 1),legend.position = 'left') + color_2


p3
```



